### ISSUE TITLE
Страница оформления заказа

### ISSUE THREAD

**Issue by lapshin-vyacheslav** [robokassa/cms-wordpress-subscriptions#6]
Алексей, здравствуйте!
Помогите, пожалуйста.
Установил плагин робокассы для WooCommerce Subscriptions и выбрал вариант через iframe .
После оформления заказа появилась дополнительная страница подтверждения заказа. И только после нее открывется поп-ап.
Подскажите, пожалуйста, какой есть вариант, чтобы поп-ап открывался сразу после оформления заказа?
Очень буду благодарен!

**Comment by avasilevrobokassa** [comment]
Пока что такого мы не реализовали, передали ваше пожелание по доработке разработчикам.

**Comment by HornCom** [comment]
Добрый день! Функционал реализован.

**Comment by lapshin-vyacheslav** [comment]
Спасибо огромное! Подскажите, пожалуйста, где включить этот редирект?

**Comment by HornCom** [comment]
Переустановите модуль, редирект включится автоматически.

**Comment by lapshin-vyacheslav** [comment]
Все работает, еще раз большое спасибо!
Но появилась проблема, после оплаты и закрытия попапа, покупатель видит такую страницу с кнопкой "Оплатить" и это может вызвать непонимание у неопытных покупателей. Я понимаю, что при оплате через iframe нельзя задавать страницу успешной оплаты. Также я понимаю, что вы не можете с этим ничего сделать. Но может вы подскажете в какую сторону копать, чтобы после оплаты, человека переадресовывало на нужную нам страницу? (Оплата на сайте Робокассы нам тоже не подходит)
Возможно стоит поискать программиста, который напишет код переадресации после закрытия попапа робокассы? Возможно это теоретически? Буду благодарен за любую гипотезу.

**Comment by lapshin-vyacheslav** [comment]
Забыл прикрепить скрин страницы после оплаты 
![image](https://user-images.githubusercontent.com/90949730/134614405-5649c28a-c6c8-494b-9f68-7cd266bd863d.png)
